server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.64.134:3100/loki/api/v1/push
#    basic_auth:
#      username: user
#      password: pass

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: nginx
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginxlogs
        __path__: /var/log/nginx/*log
    pipeline_stages:
      - match:
          selector: '{job="nginxlogs"}'
          stages:
          - regex:
              expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
          - labels:
              remote_addr:
              remote_user:
              time_local:
              method:
              request:
              protocol:
              status:
              body_bytes_sent:
              http_referer:
              http_user_agent:

  - job_name: mysql
    static_configs:
    - targets:
        - localhost
      labels:
        job: mysqllogs
        __path__: /var/log/mysql/*log


  - job_name: php
    static_configs:
    - targets:
        - localhost
      labels:
        job: phplogs
        __path__: /var/log/php*


#  - job_name: journal
#    journal:
#      max_age: 12h
#      labels:
#        job: systemd-journal
#    relabel_configs:
#      - source_labels: ['__journal__systemd_unit']
#        target_label: 'unit'
