#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir: "/var/lib/vector"

sources:
  file_nginx_access_logs:
    type: file
    include:
      - /var/log/nginx/access.log
      - /var/log/nginx/*_access_log
  file_nginx_error_logs:
    type: file
    include:
      - /var/log/nginx/error.log
      - /var/log/nginx/*_error_log
  file_php-fpm_logs:
    type: file
    include:
      - /var/log/php*.log
  file_mysql_logs:
    type: file
    include:
      - /var/log/mysql/error.log
transforms:
  nginx_logs:
    type: remap
    inputs:
      - file_nginx_access_logs
      - file_nginx_error_logs
    source: >-
      . |= parse_nginx_log!(.message, "combined")

      .app_name = "nginx"
  php-fpm_logs:
    type: remap
    inputs:
      - file_php-fpm_logs
    source: >-
      . |= parse_regex!(.message, r'\[(?P<event_date>\d+\-\w+\-\d+\s\d+\:\d+\:\d+)\] (?P<event_severity>\w+)\: (?P<event_message>.*)$')

      .app_name = "php-fpm"
  mysql_logs:
    type: remap
    inputs:
      - file_mysql_logs
    source: >-
      . |= parse_regex!(.message, r'(?P<event_date>\d+-\d+-\d+T\d+:\d+:\d+\.\d+.) (?P<event_thread>\d) \[(?P<event_label>\w+)\] \[(?P<event_err_code>\w+-\d+)\] \[(?P<event_subsystem>\w+)\] (?P<event_message>.*)$')

      .app_name = "mysql"

sinks:
  elastic:
    type: elasticsearch
    inputs:
      - nginx_logs
      - php-fpm_logs
      - mysql_logs
    endpoints:
      - https://192.168.64.133:9200
    auth:
      strategy: "basic"
      user: "elastic"
      password: "OwMMLcNdrjcG6LnZqqEB"
    tls:
      ca_file: "/etc/vector/cert/http_ca.crt"
    bulk:
      index: "ecs-vector-{{ .app_name }}-%Y-%m-%d"
# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
# api:
#   enabled: true
#   address: "127.0.0.1:8686"
