global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is >
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 >
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      site: prod
      monitor: 'example'

remote_write:
  - url: http://192.168.64.131:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_>
rule_files:
  - alerts.yml	
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from >
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-prom
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'node-wp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.128:9100']

  - job_name: 'nginx-wp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.128:9113']

  - job_name: 'pushgateway-wp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.128:9091']

  - job_name: 'mysqld-wp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.128:9104']

  - job_name: 'processmon-wp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.128:9256']

  - job_name: 'blackbox-wp'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.64.128    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.64.128:9115

  - job_name: 'node-graf'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.64.131:9100' ]

  - job_name: 'victoria'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.131:8428']  
